### ISSUE TITLE
redirecting to the docker container

### ISSUE THREAD

**Issue by SavostinVladimir** [gin-gonic/gin#2084]
- go version:
go1.12.9 linux/amd64
- gin version (or commit ref):
1.3.0
- operating system:
ubuntu
## Description
I try to redirect request from my one docker container to another...
but it does not works
there is my docker-compose.yml
```
first_service:
  build: first_service
  ports:
    - 7001:4444
  links:
       - second_service
second_service:
  build: second_service
  ports:
    - 2232:2232
 ```
there is my redirect handler:
```golang
func  redirectToSecondService(context *gin.Context) {
	//lets try to get info through http.Get! It's OK!!
	resp, _ := http.Get("http://second_service:2232/some_endpoint")
	data, _:=ioutil.ReadAll(resp.Body)
	
       //so, now let's try to redirect to the same source! It's not working!!!
	context.Redirect(http.StatusPermanentRedirect, "http://second_service:2232/some_endpoint")
      //I've just tried the "second_service:2232/some_endpoint", "second_service/some_endpoint", "//second_service:2232/some_endpoint"
}

```
I also check my link through `curl second_service:2232/some_endpoint` from my first container and it works fine too
