### ISSUE TITLE
ShouldBindYAML recognize key of string as key of interface

### ISSUE THREAD

**Issue by ScarecrowY** [gin-gonic/gin#2734]
## Description

I tried to use ```ShouldBindYAML``` to bind a sequence of objects (scenes) and marshal it to a JSON string, as the example I provide below. I defined a ```map[string]interface{}``` called ```GoObject``` and an array of ```GoObject``` called ```SceneList```. I want to put the fields that the ```Scene``` struct doesn't include in the ```Meta``` field. Although most parts worked correctly, the ```model_list``` field in the YAML object seems to be bound to the type ```map[interface{}]interface{}``` while I expected it to be ```map[string]interface{}```. And when I do ```json.marshal```, it reports the error ```json: unsupported type: map[interface {}]interface {}```. Please let me know if you need more information. 
## How to reproduce

Here is the part of code that went wrong:
```
type Scene struct{
	ID        uint64							`json:"id" gorm:"primary_key;auto_increment"`
	Name      string          					`json:"name" gorm:"unique;not null"`
	Description string        					`json:"description" gorm:"type:text"`
	Creator     string        					`json:"creator,omitempty"`
	CreatedAt   time.Time      					`json:"createdAt"`
	UpdatedAt	time.Time						`json:"updatedAt"`
	DeletedAt	gorm.DeletedAt					`json:"deletedAt" gorm:"index"`
	Vendor      string        					`json:"vendor"`
	Meta        *JsonMetaData        			`json:"template,omitempty" gorm:"type:text"`
}

type JsonMetaData struct {
	DataStr string
}

type GoObject = map[string]interface{}
type SceneList struct {
	Scene []GoObject `yaml:"scene" json:"scene"`
}
var sceneList SceneList
if err := c.ShouldBindYAML(&sceneList); err != nil {
	return nil, configs.ParameterError("invalid YAML list")
}
var scenes []*models.Scene
for _, value := range sceneList.Scene {
        scene := &models.Scene{
	        Creator: user,
	        Vendor: vendor,
        }
        
        if desc, _ := value["description"].(string); len(desc) > 0 {
	        scene.Description = desc
	        delete(value, "description")
        }
        
        if name, _ := value["name"].(string); len(name) > 0 {
	        scene.Name = name
	        delete(value, "name")
        }
        
        scene.Meta = &models.JsonMetaData{}
        dataStr, err := json.Marshal(value)
        if err != nil {
	        return nil, configs.CheckError(err, configs.TEMPLATE_INVALID_PARAMS)
        }
}
```

Here is the YAML that produced the problem:
```
scene:
  - name: "name1"
    model_flag: "det_cls"
    model_list:
      - ui_name: "u1"
        filter_type: "f1"
        default: "model"
        dataset_type: "default"
        required: true
    have_sub_model: true
    sub_model_info:
      ui_name: "u1"
      model_type: "image"
  - name: "name1"
    model_flag: "ocr"
    model_list:
      - ui_name: "u2"
        filter_type: "text"
        default: "model"
        dataset_type: ""
        required: false
      - ui_name: "text"
        filter_type: "text"
        default: "default"
        dataset_type: ""
        required: true
    have_sub_model: false
```

## Environment

- go version: go1.16.2 windows/amd64
- gin version (or commit ref): 1.7.1
- operating system: Windows 10
